### ISSUE TITLE
Don't distribute source maps

### ISSUE THREAD

**Issue by stevenhair** [ldapts/ldapts#102]
With the source maps included in ldapts builds, we get some strange and incorrect stack traces when errors happen:

```
Error: Connection timeout
    at Timeout._onTimeout (/usr/company/release/app/node_modules/src/Client.ts:712:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Note the incorrect `node_modules/src/Client.ts` path (it should be `node_modules/ldapts/Client.ts`). The `sources` field in the sourcemap is currently set to "../src/Client.ts", which is what's causing the problem. Alternatively, the build could be modified so that the paths are correct.

**Comment by jgeurts** [comment]
Thanks for letting me know, I'll take a look at how the project is built and will see if there are improvements that can be done to have more accurate source map locations

**Comment by stevenhair** [comment]
Thanks. It's not a big deal and now that we know that a stack trace like that is from ldapts, but it did take a bit to get to that point.

**Comment by stevenhair** [comment]
So after running into this myself, this can be fixed by adding the "mapRoot" option to tsconfig.json. I opened a PR.

**Comment by jgeurts** [comment]
Thanks for the PR! Please feel free to open a new issue if that doesn't solve things. It went out with v3.0.4
