### ISSUE TITLE
TypeError when trying to use client.modify 

### ISSUE THREAD

**Issue by connor-tyndall** [ldapts/ldapts#109]
This is the following error I'm receiving:

```{
  "errorType": "TypeError",
  "errorMessage": "this.modification.write is not a function",
  "trace": [
    "TypeError: this.modification.write is not a function",
    "    at Change.write (/var/task/node_modules/ldapts/Change.js:27:27)",
    "    at ModifyRequest.writeMessage (/var/task/node_modules/ldapts/messages/ModifyRequest.js:18:20)",
    "    at ModifyRequest.write (/var/task/node_modules/ldapts/messages/Message.js:19:14)",
    "    at Client._send (/var/task/node_modules/ldapts/Client.js:639:46)",
    "    at Client.modify (/var/task/node_modules/ldapts/Client.js:310:35)",
    "    at Runtime.addAdGroup [as handler] (/var/task/index.js:100:30)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  ]
}
```

Here is my code (using latest version of ldapts):

```
            const base = `CN=myGroup_${aliasUpper}${groupType},${ad_ou_path}`;

            const entry = {
                objectclass: ['top', 'group'],
                sAMAccountName: `myGroup_${aliasUpper}${groupType}`
            };
            // Add group(s)to AD
            await client.add(base, entry);

            //Modify group
            const change = new Change({
                operation: 'add',
                modification: {
                    member: base
                }
            });

            if (securityLevel !== '2') {
                await client.modify(`CN=myGroup1,${ad_ou_path}`, change);
            } else {
                await client.modify(`CN=myGroup2,${ad_ou_path}`, change);
            }
```

Please advise.

**Comment by connor-tyndall** [comment]
@jgeurts

**Comment by jgeurts** [comment]
@connor-tyndall I _think_ you may need to use an attribute class when defining the modification. Could you please try something like:

```ts
const change = new Change({
  operation: 'add',
  modification: new Attribute({
    type: 'member',
    values: [base],
  }),
});
```

**Comment by jgeurts** [comment]
Closing this due to lack of activity. Please feel free to reopen if needed!
