### ISSUE TITLE
I keep geeting TypeError: net.connect is not a function     at Client.js:516:35

### ISSUE THREAD

**Issue by ngingihy** [ldapts/ldapts#112]
I'm using angular with ldapts, i keep getting this error 

> TypeError: net.connect is not a function
>     at Client.js:516:35
> 

Here is my typescript code

```
  async test() {
    const client = new Client({
        url: "ldap://ldap.test.com:389",
        connectTimeout: 5000,
        timeout: 5000,
    });

    try {
        console.log("no error");
        
        await client.bind("norhan_kotb", "123456");
        console.log("no error")
        // console.log(client.bind("non-existing"))
    } catch (e) {
        console.timeEnd("time");
        console.log("errrrrrrr")
        console.log(e)
    }
    console.log("testtt")
    console.log(client)

}


  onClick() {
    this.test();
}
```
this is my temp .html 
`  <button (click)="onClick()" class="btn btn-primary">Click Me</button>
`

**Comment by jgeurts** [comment]
This library likely won't work in a browser as it is currently written & deployed. It's meant more for the server side and node.js.
