### ISSUE TITLE
Adding support for binding user with email address

### ISSUE THREAD

**Issue by byujiang** [ldapts/ldapts#117]
Currently ldapts doesn't support binding user with email address, and only supports binding with the username.  So any plan to adding the email binding support?

The following is the error when I tried to bind with email address:
```bash
/tmp/ldap/node_modules/ldapts/StatusCodeParser.js:54
                return new resultCodeErrors_1.InvalidCredentialsError(message);
                       ^

InvalidCredentialsError: Invalid credentials during a bind operation. Code: 0x31
    at Function.parse (/tmp/ldap/node_modules/ldapts/StatusCodeParser.js:54:24)
    at Client.bind (/tmp/ldap/node_modules/ldapts/Client.js:161:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 49
}
```

**Comment by jgeurts** [comment]
Closing due to inactivity. Please reopen if you're still having troubles!
