### ISSUE TITLE
Error [InvalidAsn1Error]: Expected 0x4: got 0x43

### ISSUE THREAD

**Issue by ixevix** [ldapts/ldapts#151]
Hi, sometimes Client search fails with following error

```
Error [InvalidAsn1Error]: Expected 0x4: got 0x43
    at newInvalidAsn1Error (/app/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader.readString (/app/node_modules/asn1/lib/ber/reader.js:169:11)
    at Attribute.parse (/app/node_modules/ldapts/Attribute.js:44:43)
    at SearchEntry.parseMessage (/app/node_modules/ldapts/messages/SearchEntry.js:20:23)
    at SearchEntry.parse (/app/node_modules/ldapts/messages/Message.js:33:14)
    at MessageParser._getMessageFromProtocolOperation (/app/node_modules/ldapts/MessageParser.js:160:17)
    at MessageParser.read (/app/node_modules/ldapts/MessageParser.js:75:34)
    at Client.socketDataHandler (/app/node_modules/ldapts/Client.js:54:36)
    at TLSSocket.emit (node:events:529:35)
    at addChunk (node:internal/streams/readable:368:12) {
  messageDetails: { messageId: 86, protocolOperation: 100 }
}
```
Could this be related to the asn1 library being used? I noticed some disussion [here](https://github.com/ldapts/ldapts/issues/7) about using the same asn1 library as in ldapjs but they have since swapped out the one that is being used.
Here is the first commit in ldapjs when swapping it out. They have since updated it as well https://github.com/ldapjs/node-ldapjs/commit/9fe58a44a2284e742b783bf98c810fdaec6f4cbb

**Comment by thernstig** [comment]
@ixevix which version of Node.js are you using? https://github.com/ldapts/ldapts/issues/7#issuecomment-460607978 mentions it works after using a newer Node,js version.

**Comment by ixevix** [comment]
18. Those versions they are talking about are _really_ old

**Comment by ixevix** [comment]
After switching to use ldapjs instead I have been running without these errors.

**Comment by ayZagen** [comment]
@ixevix Can you try version `7.7.2` ? I think it may be fixed with the fix landed in #162

**Comment by ixevix** [comment]
As I stated previously switched to ldapjs so can't verify the fix.

**Comment by HNA-JP** [comment]
I'm also having this issue when doing some thing equivalent to the following:
```js

let ldapFilter = "(distinguishedName=<anonymized valid distinguished name>)"

/* Execute search */
try {
    /* Bind the LDAP client so we can make queries */
    await client.bind(process.env.LDAP_CN, process.env.LDAP_PW);

    /* Do a search */
    let { searchEntries } = await client.search("<ldap base anonymized>", { filter: ldapFilter })
        
    /* Return the first entry */
    return searchEntries[0]

} catch (err) {
    /* Throw error */
    throw "Active Directory returned an error"

} finally {
    /* Unbind the LDAP client now that we're done */
    await client.unbind();
}
```
