### ISSUE TITLE
Client EXOP fails with TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by d95sld95** [ldapts/ldapts#52]
Using Active Directory this function fails in the method ldapClient.exop(....)

```
export async function authenticate(username, password) {

    // Declare ldap client connection once and enable reconnect
    // and listen for connect events (see below)
    const ldapClient = new Client({
        url: `ldap://${config.ldapHost}`,
        reconnect: {
            initialDelay: 100,
            maxDelay: 1000,
            failAfter: 10
        },
    });
    await ldapClient.exop('1.2.840.113556.1.4.1781'); // throws error 'toString' of null
    await ldapClient.bind(username ,password);
    await ldapClient.unbind();
}
```

I get this stack trace

```
TypeError: Cannot read property 'toString' of null
    at new ResultCodeError (/Users/slaursen/dev10/deploy/ep-auth-server/node_modules/ldapts/errors/resultCodeErrors/ResultCodeError.js:7:51)
    at new UnknownStatusCodeError (/Users/slaursen/dev10/deploy/ep-auth-server/node_modules/ldapts/errors/resultCodeErrors/UnknownStatusCodeError.js:6:9)
    at Function.parse (/Users/slaursen/dev10/deploy/ep-auth-server/node_modules/ldapts/StatusCodeParser.js:80:24)
    at Client.exop (/Users/slaursen/dev10/deploy/ep-auth-server/node_modules/ldapts/Client.js:218:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by d95sld95** [comment]
Line 216 in the client does return a result object like this:

```
{
  "version": 3,
  "messageId": 2,
  "controls": [],
  "status": null,    <----- Status is NULL
  "matchedDN": null,
  "errorMessage": null,
  "protocolOperation": 120,
  "oid": "1.2.840.113556.1.4.1781"
}
```

**Comment by d95sld95** [comment]
If I provide an invalid OID, this is the response I get

```
{
  "version": 3,
  "messageId": 2,
  "controls": [],
  "status": null,
  "matchedDN": null,
  "errorMessage": null,
  "protocolOperation": 120,
  "oid": undefined,           <---- NOW UNDEFINED INSTEAD OF VALUE
  "value": undefined
}
```

**Comment by d95sld95** [comment]
ps. ldap.js returns status of 0.

**Comment by jgeurts** [comment]
Thanks for letting me know! I’ll see about reproducing this with a test and public ldap server. Once there’s a unit test, I can get a fix out quickly. 

Feel free to submit a unit test reproducing this with jumpcloud or forumsys, if you have the time.
