### ISSUE TITLE
Compare does not work with read only user.

### ISSUE THREAD

**Issue by wmantly** [ldapts/ldapts#79]
When bind with a read-only user and try to use compare, I get this message:

```
InsufficientAccessError: The caller does not have sufficient rights to perform the requested operation. Code: 0x32
    at Function.parse (/home/william/dev/wmantly/ldap-node-test/node_modules/ldapts/StatusCodeParser.js:53:24)
    at Client.compare (/home/william/dev/wmantly/ldap-node-test/node_modules/ldapts/Client.js:202:59)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/william/dev/wmantly/ldap-node-test/app.js:26:16 {
  code: 50,
  message: 'The caller does not have sufficient rights to perform the requested operation. Code: 0x32'
}
```

**Comment by wmantly** [comment]
This can be closed, it was my mistake.
